services:
  postgres:
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4
    ports:
      - 6379:6379
      - 8001:8001
    expose:
      - 6379
      - 8001

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80

  url_shortner_service:
    image: url_shortner_service:latest
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - DSN=postgres://root:root@postgres:5432/postgres?sslmode=disable
      - REDIS_CLIENT_ADDR=redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres-data:
